from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')  + Glob('*.s') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('clib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
