from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.s') + Glob('*.S')
CPPPATH = [cwd]

group = DefineGroup('newlib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
